[package]
name = "trash"
version = "1.1.1"
authors = ["Artur Kovacs <kovacs.artur.barnabas@gmail.com>"]
license = "MIT"
readme = "Readme.md"
description = "A library for moving files and folders to the OS's Trash or Recycle Bin"
keywords = ["remove", "trash", "rubbish", "recycle", "bin"]
repository = "https://github.com/ArturKovacs/trash"
edition = "2018"

[dependencies]

[target.'cfg(windows)'.dependencies]
winapi = { version = "^0.3.0", features = ["shellapi", "winerror"] } 
